feat: modify cluster overview
devtron-labs/dashboard pull request #1412
Opened 2023-10-25 18:34 UTC by mukultayal135

# Description

Cluster Overview tab moved to fixed tabs and cluster details added as sidebar in overview

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2023-10-27 13:38 UTC, eshankvaish requested changes

2023-10-27 13:39 UTC, eshankvaish commented
Reviewed related to reusability and not complete functionality

2023-10-30 04:26 UTC, mukultayal135 commented on src/components/ClusterNodes/clusterNodes.service.tsx
>  export const getClusterNote = (clusterId: string): Promise<ClusterDescriptionResponse> => {
URL as in for API?

2023-10-30 04:27 UTC, mukultayal135 commented on src/components/common/Description/GenericDescription.tsx
> +                                Readme
Icon is updated need to connect for second point

2023-10-30 04:35 UTC, eshankvaish commented on src/components/ClusterNodes/clusterNodes.service.tsx
>  export const getClusterNote = (clusterId: string): Promise<ClusterDescriptionResponse> => {
The function name is getClusterNote while the API URL being used is CLUSTER_DESCRIPTION

2023-10-30 04:40 UTC, eshankvaish requested changes

2023-10-30 04:40 UTC, eshankvaish commented on src/components/common/Description/GenericDescription.tsx
> +                                Readme
Referring to the constants for the null & error states: https://github.com/devtron-labs/dashboard/pull/1412/files/ed4e9e81b5f87a752168a6bf46982c7c94988d48#diff-21a7f12b16e2ff18b58a60adbf9a7e60d8795ecc092f25e2d25c9bfa427a81f4R30 

Also I think the icon has been updated in the figma

2023-10-30 06:06 UTC, vivek-devtron commented on src/components/ClusterNodes/ClusterOverview.tsx
> +    sideDataAbortController,
Why is this required?

2023-10-30 06:08 UTC, vivek-devtron commented on src/components/ClusterNodes/ClusterOverview.tsx
> +        if (clusterNoteResponse.status === 'fulfilled') {
Break this into smaller functions

2023-10-30 06:09 UTC, vivek-devtron commented on src/components/ClusterNodes/ClusterOverview.tsx
> +                _date = _moment.isValid() ? _moment.format(Moment12HourFormat) : _clusterNote.updatedOn
We can directly use this instead of creating new var

2023-10-30 06:10 UTC, vivek-devtron commented on src/components/ClusterNodes/ClusterOverview.tsx
> +        if (clusterNoteResponse.status === 'rejected') {
This should be else part of fullfilled

2023-10-30 06:10 UTC, vivek-devtron commented on src/components/ClusterNodes/ClusterOverview.tsx
> +        if (clusterCapacityResponse.status === 'rejected') {
same for this

2023-10-30 06:10 UTC, vivek-devtron commented on src/components/ClusterNodes/ClusterOverview.tsx
> +        ;(async () => {
Please fix this formatting

2023-10-30 06:11 UTC, vivek-devtron commented on src/components/ClusterNodes/ClusterOverview.tsx
> +    // const cardDetailsInBar = () => {
Please remove commented code

2023-10-30 08:10 UTC, vivek-devtron approved these changes

2023-10-30 08:44 UTC, merged