fixes(app-dependency): GA and Qa bigs
devtron-labs/dashboard pull request #1522
Opened 2023-12-12 11:45 UTC by ritvikmahajan17

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2023-12-12 13:28 UTC, eshankvaish requested changes

2023-12-12 13:28 UTC, eshankvaish commented on src/components/app/Overview/Overview.tsx
> +        })
This event should be fired while Opening the modal I guess.

2023-12-13 06:23 UTC, eshankvaish approved these changes

2023-12-13 07:54 UTC, vivek-devtron approved these changes

2023-12-22 11:06 UTC, merged