fix: add optional chaining in AdvancedConfigOptions.tsx
devtron-labs/dashboard pull request #1641
Opened 2024-02-22 05:45 UTC by arunjaindev

# Description
Bug Fix

Fixes https://github.com/devtron-labs/devtron/issues/4709         https://github.com/devtron-labs/devtron/issues/4712

## Type of change
- [x] Bug fix 

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-02-22 09:32 UTC, eshankvaish requested changes

2024-02-22 09:32 UTC, eshankvaish commented on src/components/bulkEdits/bulkedits.service.tsx
> +    kind = kind?.toLocaleLowerCase()
- We don't need both String and `` operator
- what if the kind is undefined?

2024-03-01 05:36 UTC, AbhishekA1509 commented on src/components/app/details/appDetails/AppDetails.tsx
> +                showError(err);
use prettier

2024-03-01 05:36 UTC, AbhishekA1509 commented on src/components/app/details/triggerView/TriggerView.tsx
>      // FIXME: Seems like its missing a error state
Can you now remove this comment?

2024-03-01 05:37 UTC, AbhishekA1509 commented on src/components/bulkEdits/BulkEdits.tsx
> +                throw new Error('provide kind')
We can make it a constant

2024-03-01 05:39 UTC, AbhishekA1509 commented on src/components/bulkEdits/BulkEdits.tsx
> +            if (configJson.kind === undefined) {
Please verify if we can write as if (!configJson.kind) {}

2024-03-01 05:39 UTC, AbhishekA1509 commented on src/components/bulkEdits/BulkEdits.tsx
> +            } else toast.error('Invalid Yaml') // Invalid YAML, couldn't be parsed to JSON. Show error toast
please use prettier here

2024-03-01 05:40 UTC, AbhishekA1509 commented on src/components/bulkEdits/BulkEdits.tsx
> +            if (configJson.kind === undefined) {
Can we remove this duplication by encapsulating it in a function?

2024-03-01 05:40 UTC, AbhishekA1509 commented on src/components/bulkEdits/bulkedits.service.tsx
> +    let kind = `${request.kind}`
Don't use let chain the expressions and use const

2024-03-01 05:42 UTC, AbhishekA1509 commented on src/components/v2/appDetails/AppDetails.component.tsx
> +                getSaveTelemetry(params.appId)
Can you verify loaders?

2024-03-04 08:21 UTC, AbhishekA1509 commented on src/components/bulkEdits/BulkEdits.tsx
> +            } else toast.error('Invalid Yaml') // Invalid YAML, couldn't be parsed to JSON. Show error toast
Also verify viewType being set to FORM

2024-09-11 07:37 UTC, closed without merging