feat: linked-ci-details modal
devtron-labs/dashboard pull request #1672
Opened 2024-03-14 13:42 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-03-14 14:06 UTC, eshankvaish requested changes

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +        <div className="">
- remove empty className
- Use direct arrow function return
- Move to separate files

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +            <div className="flexbox bcn-0 dc__uppercase pl-20 pr-20 pt-6 pb-6 dc__border-bottom dc__align-self-stretch dc__align-center dc__gap-16 fs-12 fw-6 dc__content-space">
Group similar classes, add line height. We can ditch the padding blocks and use grid-auto-row to define row height
```suggestion
            <div className="flex dc__gap-16 bcn-0 dc__uppercase pl-20 pr-20 pt-6 pb-6 dc__border-bottom fs-12 fw-6 dc__content-space">
```

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +            <div className="flexbox bcn-0 dc__uppercase pl-20 pr-20 pt-6 pb-6 dc__border-bottom dc__align-self-stretch dc__align-center dc__gap-16 fs-12 fw-6 dc__content-space">
The layout would not have any relationship b/w rows. PS: use grid

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                    disabled={false}
add TODO

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +            <div className="flexbox-col bcn-0 dc__overflow-scroll">
same as above for layout

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +import AppListData from './constants'
- camelCase
- Use service for mock, api integration

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                {AppListData.map((appRowData) => (
```suggestion
                {AppListData.map((appData) => (
```

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                    />
```suggestion
                    <AppListRow
                        {...appData}
                    />
```

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +        <div className="flexbox pl-20 pr-20 pt-8 pb-8 dc__align-self-stretch dc__align-center dc__gap-16 fs-13 fw-4 dc__content-space">
same styling issue

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +            <span> {deploymentStatus} </span>
ellipsis are missing

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +        <div className="flexbox pl-20 pr-20 pt-8 pb-8 dc__align-self-stretch dc__align-center dc__gap-16 fs-13 fw-4 dc__content-space">
color is missing

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +        <div className="flexbox pl-20 pr-20 pt-8 pb-8 dc__align-self-stretch dc__align-center dc__gap-16 fs-13 fw-4 dc__content-space">
hyperlinking is missing. We should potentially use Link component from react router dom

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +}
move to types

2024-03-14 14:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +export interface AppListRowDataType {
```suggestion
export interface LinkedCIAppList {
```

2024-03-15 09:53 UTC, eshankvaish requested changes

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/types.ts
> +}
```suggestion
export interface LinkedCIDetailModalProps {
    ciPipelineName: string
    linkedWorkflowCount: number
}

export interface LinkedCIAppDto {
    appName: string
    environment: string
    triggerMode: string
    deploymentStatus: string
}
```

2024-03-15 09:53 UTC, eshankvaish commented on src/components/app/details/triggerView/workflow/nodes/triggerCINode.tsx
> +        e.stopPropagation()
Remove the comment, and add comment for stopPropagation

2024-03-15 09:53 UTC, eshankvaish commented on src/components/app/details/triggerView/workflow/nodes/triggerCINode.tsx
> +                            content={`Build Pipeline is linked as image source in ${this.props.linkedCount} ${this.props.linkedCount === 1 ? 'workflow.' : 'workflows.'}`}
```suggestion
                            content={`Build Pipeline is linked as image source in ${this.props.linkedCount} ${this.props.linkedCount === 1 ? 'workflow' : 'workflows'}.`}
```

2024-03-15 09:53 UTC, eshankvaish commented on src/components/app/details/triggerView/workflow/nodes/triggerCINode.tsx
> +                                    {this.props.isJobCI ? ' Job ' : ' Build '}
verify the spaces

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/linkedCIAppList.scss
> +    align-items: center;
use utility for grid and align items center

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/linkedCIAppList.scss
> +.linked-ci-apps {
```suggestion
.linked-ci-detail {
    &__table-row {
```

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetails.tsx
> +const LinkedCIDetails = ({ ciPipelineName, linkedWorkflowCount }: LinkedCIDetailsModalProps) => {
```suggestion
const LinkedCIDetail = (props: LinkedCIDetailsModalProps) => {
```

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetails.tsx
> +                    <LinkedCIDetailsModal ciPipelineName={ciPipelineName} linkedWorkflowCount={linkedWorkflowCount} />
```suggestion
                    <LinkedCIDetailsModal {...props} />
```

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIAppList.tsx
> +    }
use useUrlFilter for such state

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIAppList.tsx
> +        <div>
add flex probably

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +    return (
- use direct return
- add default for pipelineName and count

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                    <button type="button" className="dc__transparent flex icon-dim-24" aria-label="close-modal">
```suggestion
                    <button type="button" className="dc__transparent flex dc__no-shrink" aria-label="close-modal">
```

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                    <h2 className="fs-16 fw-6 lh-24 m-0">{ciPipelineName}</h2>
ellipsis handling

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                        message={`This build pipeline is linked as image source in ${linkedWorkflowCount} ${linkedWorkflowCount === 1 ? 'workflow.' : 'workflows.'}`}
common out using a function

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                        classname="info_bar justify-start"
check for justify-start

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                <div>
flex

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                            />
make sure to add the check for DEFAULT_PAGE_SIZE

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                        <div className="dc__no-shrink">
the class is redundant

2024-03-15 09:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIAppList.tsx
> +            <div className="linked-ci-apps pl-20 pr-20 pt-8 pb-8 fs-13 fw-4 dc__hover-n50 ">
add color to header and row

2024-03-19 11:53 UTC, eshankvaish requested changes

2024-03-19 11:53 UTC, eshankvaish commented on src/components/app/details/triggerView/workflow/nodes/triggerCINode.tsx
> +                        content={LinkedCITippyContent(this.props.linkedCount)}
```suggestion
                        content={getLinkedCITippyContent(this.props.linkedCount)}
```

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/utils.ts
> +    environment: searchParams.get('environment') || SELECT_ALL_VALUE,
move 'environment' to constants. ENVIRONMENT_FILTER_SEARCH_KEY

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/utils.ts
> +export const LinkedCITippyContent = (workflowCount: number) => {
direct arrow function return

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/types.ts
> +export interface LinkedCIAppListProps {
```suggestion
export type CIPipelineEnviromentList = string[]

export interface LinkedCIAppListProps {
```

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/index.ts
> +export { default as LinkedCIDetail } from './LinkedCIDetail'
check if the comment can be removed after back merge from main

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/constants.ts
> +        deploymentStatus: 'succeeded',
use from the object

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/constants.ts
> +export const DEFAULT_ALL_ENV = { label: 'All Environments', value: SELECT_ALL_VALUE }
```suggestion
export const ALL_ENVIRONMENTS_OPTION = { label: 'All Environments', value: SELECT_ALL_VALUE }
```

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +    const commonStyles = getCommonSelectStyle()
move to constants

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +    }
use from constant

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetail.tsx
> +            />
check for children vs render

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetail.tsx
> +            />
wrap with drawer here

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                                }}
move to constants. environmentFilterDropdownStyles

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
> +                ) : null}
use &&

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIAppList.tsx
> +    return (
direct arrow function return

2024-03-19 11:53 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/LinkedCIAppList.tsx
> +    )
move inside the if

2024-03-19 12:41 UTC, eshankvaish submitted a review, later dismissed

2024-03-19 13:29 UTC, AbhishekA1509 commented on src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
> +        const handleModalClose = () => {
Its anti pattern to have functions inside function

2024-03-19 13:30 UTC, AbhishekA1509 commented on src/components/app/details/triggerView/TriggerView.tsx
> +        const handleModalClose = () => {
Same here

2024-03-20 07:22 UTC, eshankvaish submitted a review, later dismissed

2024-03-20 13:06 UTC, eshankvaish requested changes

2024-03-20 13:06 UTC, eshankvaish commented on src/Pages/Shared/LinkedCIDetailsModal/utils.ts
> +import { LinkedCIAppURLProps as LinkedCIAppUrlProps } from './types'
fix the issue

2024-03-20 13:06 UTC, eshankvaish commented on src/components/app/details/triggerView/workflow/nodes/triggerCINode.tsx
> +                        <button type="button" className="link-count cursor dc__hover-border-n300" onClick={this.handleLinkedCIWorkflowChipClick}>
verify the styling for the button

2024-03-20 13:45 UTC, eshankvaish approved these changes
LGTM

2024-03-21 05:54 UTC, vivek-devtron submitted a review, later dismissed

2024-03-21 12:18 UTC, vivek-devtron approved these changes

2024-03-21 12:20 UTC, merged