chore - Made a component file for docker image Details
devtron-labs/dashboard pull request #1676
Opened 2024-03-18 10:27 UTC by randhir-devtron

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-03-18 11:38 UTC, AbhishekA1509 commented on src/components/v2/chartDeploymentHistory/DockerImageDetails.tsx
> +                        <span className="">{deployment.dockerImages.length - 3}</span>
Why are we setting "" as className

2024-03-18 11:39 UTC, AbhishekA1509 commented on src/components/v2/chartDeploymentHistory/DockerImageDetails.tsx
> +                        <span className="ml-3">more</span>
if possible avoid margins

2024-03-18 11:40 UTC, AbhishekA1509 commented on src/components/v2/chartDeploymentHistory/DockerImageDetails.tsx
> +}: {
Move it to interface

2024-03-18 11:41 UTC, AbhishekA1509 commented on src/components/v2/chartDeploymentHistory/DockerImageDetails.tsx
> +import docker from '../../../assets/icons/misc/docker.svg'
Check if we can import as ReactComponent

2024-03-18 11:42 UTC, AbhishekA1509 requested changes

2024-03-18 11:42 UTC, AbhishekA1509 commented on src/components/v2/chartDeploymentHistory/DockerImageDetails.tsx
> +}: {
And move it to separate file

2024-03-18 11:48 UTC, AbhishekA1509 commented on src/components/v2/chartDeploymentHistory/DockerImageDetails.tsx
> +                <div onClick={() => setShowDockerInfo(true)} className="cursor anchor ml-10">
use button if we are setting onClick

2024-03-20 05:57 UTC, AbhishekA1509 commented on src/components/v2/chartDeploymentHistory/DockerImageDetails.tsx
> +        <div>
Can we use React Fragment

2024-03-20 06:00 UTC, AbhishekA1509 commented on src/components/v2/chartDeploymentHistory/DockerImageDetails.tsx
> +            {deployment.dockerImages.slice(0, 3).map((dockerImage, index) => {
@vivek-devtron will dockerImage be unique?

2024-03-20 07:30 UTC, AbhishekA1509 approved these changes

2024-03-21 06:12 UTC, vivek-devtron approved these changes

2024-04-16 05:26 UTC, closed without merging