chore: changes some names
devtron-labs/dashboard pull request #1682
Opened 2024-03-21 16:42 UTC by randhir-devtron

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-03-27 14:10 UTC, AbhishekA1509 requested changes

2024-03-27 14:20 UTC, AbhishekA1509 commented on src/components/app/details/appConfig/EnvironmentOverrideRouter.tsx
> +                    classname="ICHelpOutline-bar no-env-overrides"
Are you sure this will work

2024-03-27 14:33 UTC, AbhishekA1509 commented on src/components/CustomChart/CustomChartList.tsx
> +                    placement="right"
Check if we can remove placement prop

2024-03-27 14:34 UTC, AbhishekA1509 requested changes

2024-03-27 14:34 UTC, AbhishekA1509 commented on src/components/app/list/AppListView.tsx
> +import { TIPPY_ICON_DIM } from '../../../../../devtron-fe-common-lib/src/Common/Constants'
Fix this and do a self review first

2024-03-27 14:35 UTC, AbhishekA1509 commented on src/components/ClusterNodes/ClusterOverview.tsx
> +                    infoText=""
it should be optional

2024-03-31 07:40 UTC, randhir-devtron commented on src/components/ConfigMapSecret/Types.ts
>      infoText: string
This is a Duplicate, Delete this

2024-03-31 07:46 UTC, randhir-devtron commented on src/components/charts/list/ChartListPopUp.tsx
>                      Icon={Help}
Are you sure this will work?

2024-03-31 07:49 UTC, randhir-devtron commented on src/components/externalLinks/ExternalLinks.tsx
> +            {renderExternalLinksContainer()}
Fix this line

2024-04-01 08:17 UTC, AbhishekA1509 commented on src/components/ClusterNodes/NodeActions/DeleteNodeModal.tsx
> -                iconClass="fcv-5"
Why are we removing this

2024-04-01 08:19 UTC, AbhishekA1509 commented on src/components/CustomChart/CustomChartList.tsx
> +            <>
Do we need this fragment?

2024-04-01 08:42 UTC, AbhishekA1509 requested changes

2024-04-01 08:42 UTC, AbhishekA1509 commented on src/components/app/details/appConfig/EnvironmentOverrideRouter.tsx
> -                    iconClass="fcv-5"
why are we removing this?

2024-04-01 08:42 UTC, AbhishekA1509 commented on src/components/app/details/appDetails/DeployedCommitCard.tsx
> -// import { ReactComponent as GitHub } from '../../../../assets/icons/git/github.svg'
Remove this comment

2024-04-01 08:42 UTC, AbhishekA1509 commented on src/components/app/list/AppListView.tsx
> +                                            <p className="dc__truncate-text  m-0 value" data-testid="app-list-for-sort">
remove extra space in className

2024-04-01 08:42 UTC, AbhishekA1509 commented on src/components/cluster/ClusterInstallStatus.tsx
>  const handleQuestion = () => {
why can't we use InfoIconTippy here?

2024-04-01 08:42 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.utils.tsx
> +                    infoText=""
It should be optional

2024-04-01 08:42 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.utils.tsx
> +                    infoText=""
Same here

2024-04-01 08:42 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.utils.tsx
> +                    className="icon-dim-16 fcn-6 mr-8"
Check for fcn-6 requirement?

2024-04-02 08:33 UTC, AbhishekA1509 approved these changes

2024-04-14 06:12 UTC, vivek-devtron commented on package.json
> +        "@devtron-labs/devtron-fe-common-lib": "0.0.71",
Please fix the version

2024-04-14 06:13 UTC, vivek-devtron commented on package.json
> +        "http-proxy-middleware": "^2.0.6",
this is removed from main. Please sync with main

2024-04-15 07:41 UTC, vivek-devtron submitted a review, later dismissed

2024-04-19 10:23 UTC, vivek-devtron approved these changes

2024-04-19 10:34 UTC, merged