refactor: component migration
devtron-labs/dashboard pull request #1701
Opened 2024-04-03 08:49 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-04-04 09:53 UTC, eshankvaish commented on src/components/common/formFields/ButtonWithLoader.tsx
> +
.

2024-04-04 09:56 UTC, eshankvaish commented on src/components/app/list-new/AppList.tsx
> +import HeaderWithCreateButton from '@devtron-labs/devtron-fe-common-lib'
.

2024-04-04 10:02 UTC, eshankvaish requested changes

2024-04-04 10:12 UTC, eshankvaish commented on src/components/Jobs/JobList/JobsList.tsx
> +import HeaderWithCreateButton from '@devtron-labs/devtron-fe-common-lib'
bump common lib version

2024-04-08 10:41 UTC, vivek-devtron approved these changes

2024-04-08 12:32 UTC, AbhishekA1509 requested changes
Please remove sonar cloud issues and btw, try to have external imports as first one

2024-04-08 13:00 UTC, AbhishekA1509 approved these changes

2024-04-08 13:25 UTC, eshankvaish approved these changes

2024-04-08 14:00 UTC, vivek-devtron approved these changes

2024-04-08 14:01 UTC, merged