feat: flux cd app details
devtron-labs/dashboard pull request #1863
Opened 2024-06-27 11:49 UTC by arunjaindev

# Description
Feature: FluxCD app details

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas

2024-06-27 13:00 UTC, AbhishekA1509 requested changes

2024-06-28 10:02 UTC, AbhishekA1509 requested changes

2024-06-28 10:51 UTC, arunjaindev commented on src/Pages/App/Details/ExternalFlux/ExternalFluxAppDetails.tsx
> +    useInterval(reloadAppDetails, 30000)
please confirm whether it should be setInterval or setTimeout ?

2024-06-28 10:57 UTC, arunjaindev commented on src/assets/icons/ic-argocd-app.svg
> +<g clip-path="url(#clip0_6967_6190)">
will verify with main while merging

2024-06-28 11:05 UTC, arunjaindev commented on src/Pages/App/Details/ExternalFlux/types.tsx
> +export interface ExternalFluxAppDetailParams {
no interface exists of such kind as of now

2024-06-28 11:14 UTC, arunjaindev commented on src/components/v2/appDetails/sourceInfo/utils.tsx
> +): string | JSX.Element => {
gives linting error

2024-07-02 10:30 UTC, vivek-devtron commented on src/Pages/App/Details/ExternalFlux/utils.tsx
> +    if (appStatus === 'True') {
Please add comments here

2024-07-02 13:03 UTC, vivek-devtron commented on src/Pages/App/Details/ExternalFlux/ExternalFluxAppDetails.tsx
> +    let initTimer = null
This should be outside of the component

2024-07-02 13:05 UTC, vivek-devtron commented on src/Pages/App/Details/ExternalFlux/ExternalFluxAppDetails.tsx
> +    const isLoading = isAppDetailsLoading && (!appDetailsResult || appDetailsError)
we should move this line at line no 77 and remove the `appDetailsError` condition

2024-07-04 10:29 UTC, vivek-devtron approved these changes

2024-07-04 10:30 UTC, merged