fix: remove docker args and override docker args from save ci pipeline payload conditionally
devtron-labs/dashboard pull request #1877
Opened 2024-07-04 12:32 UTC by eshankvaish

# Description

- fix: remove docker args and override docker args from save ci pipeline payload conditionally

Fixes https://github.com/devtron-labs/devtron/issues/5404

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-07-05 06:35 UTC, AbhishekA1509 requested changes

2024-07-05 07:01 UTC, AbhishekA1509 submitted a review, later dismissed

2024-07-26 10:46 UTC, eshankvaish commented on src/components/ciPipeline/utils.ts
> +    delete updatedConfig?.ciBuildConfig?.dockerBuildConfig?.args
deleting this is expected as confirmed with BE

2024-07-29 08:31 UTC, vivek-devtron approved these changes

2024-08-07 11:05 UTC, eshankvaish commented
Closing as this was handled on BE by @prkhrkat

2024-08-07 11:05 UTC, closed without merging