feat: download terminal files
devtron-labs/dashboard pull request #1883
Opened 2024-07-08 09:03 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-07-10 06:16 UTC, AbhishekA1509 requested changes

2024-07-10 06:16 UTC, AbhishekA1509 commented on src/components/ClusterNodes/ClusterTerminal.tsx
> +                    containerName={debugMode ? 'debugger' : 'devtron-debug-terminal'}
Can create a const and replace that in ephemeral environment file

2024-07-10 06:16 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.utils.tsx
> +const downloadFileFolderButton = (elementData) => {
Can extend type from terminalStripTypeData through Parameters and add return type and ideally should be a component

2024-07-10 06:16 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.util.ts
> +import { decode, K8sResourcePayloadAppType } from '@devtron-labs/devtron-fe-common-lib'
external import should be at top

2024-07-10 13:37 UTC, AbhishekA1509 approved these changes

2024-07-10 13:37 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.type.ts
> +export type ElementData = any
Suggestion: if have time, can we add some types for this

2024-07-10 13:37 UTC, AbhishekA1509 requested changes

2024-07-11 07:44 UTC, AbhishekA1509 requested changes

2024-07-11 07:44 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.utils.tsx
> +const downloadFileFolderButton = (elementData: ElementData): JSX.Element => {
This should be component since should contain state for showing modal and modal would be opened through this.

2024-07-11 11:03 UTC, AbhishekA1509 submitted a review, later dismissed

2024-07-12 04:34 UTC, vivek-devtron commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
> +import { importComponentFromFELibrary } from '../../../../../common'
Remove this unused import

2024-07-12 08:04 UTC, vivek-devtron approved these changes

2024-07-29 10:45 UTC, vivek-devtron approved these changes

2024-07-29 10:56 UTC, merged