feat: flux cd resources
devtron-labs/dashboard pull request #1888
Opened 2024-07-09 08:51 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-07-22 05:47 UTC, AbhishekA1509 requested changes

2024-07-22 05:47 UTC, AbhishekA1509 commented on src/components/v2/appDetails/appDetails.api.ts
> +                : getAppId(clusterId, namespace, appName, fluxTemplateType ?? null),
Can move params to object.

2024-07-22 05:47 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts
> +        return `${clusterId}|${namespace}|${appName}|${templateType === 'Kustomization'}`
Use enum

2024-07-22 05:47 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.util.ts
>      if (appType === AppType.EXTERNAL_ARGO_APP) {
Can add return type of K8sResourcePayloadAppType to function

2024-07-22 05:47 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.util.ts
> +        return K8sResourcePayloadDeploymentType.HELM_INSTALLED
Can add return type to method of K8sResourcePayloadDeploymentType

2024-07-22 05:47 UTC, AbhishekA1509 commented on src/components/v2/appDetails/AppDetails.component.tsx
> +            (appDetails?.deploymentAppType === DeploymentAppTypes.GITOPS ||
can create a variable with meaningful name like isHelmApp

2024-07-22 05:47 UTC, AbhishekA1509 commented on src/components/v2/appDetails/sourceInfo/EnvironmentSelector.component.tsx
> +                            )) ||
Please add comment for this condition

2024-07-22 05:47 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.util.ts
> +import { decode, DeploymentAppTypes } from '@devtron-labs/devtron-fe-common-lib'
can move to top

2024-07-22 05:54 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts
>      appName: string,
Can we transform params into object for deleteEphemeralUrl and generateEphemeralUrl

2024-07-22 07:25 UTC, AbhishekA1509 approved these changes

2024-08-09 11:51 UTC, vivek-devtron approved these changes

2024-08-09 11:57 UTC, merged