chore: use useDownload globally
devtron-labs/dashboard pull request #1900
Opened 2024-07-12 12:19 UTC by arunjaindev

# Description
use useDownload Hook globally to download files/folders

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas

2024-07-18 06:58 UTC, AbhishekA1509 requested changes

2024-07-18 11:58 UTC, AbhishekA1509 requested changes

2024-07-18 11:58 UTC, AbhishekA1509 commented on src/components/ApplicationGroup/Details/TriggerView/TriggerModalTableRow.tsx
> +        setIsDownloaded(true)
in case of error what will be the behavior.

2024-07-18 11:58 UTC, AbhishekA1509 commented on src/components/app/details/triggerView/cdMaterial.tsx
> +            fileName: downloadManifestDownload.appName,
Verify download file name

2024-07-19 07:55 UTC, arunjaindev commented on src/components/app/details/triggerView/cdMaterial.tsx
> +            fileName: downloadManifestDownload.appName,
Will be changing later

2024-07-19 07:56 UTC, AbhishekA1509 approved these changes

2024-07-26 12:48 UTC, vivek-devtron approved these changes

2024-07-26 13:13 UTC, merged