fix: retain filters in helm app list
devtron-labs/dashboard pull request #1914
Opened 2024-07-23 05:24 UTC by arunjaindev

# Description
fix: filters are not applied when we come back to app listing through app detail

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas

2024-07-23 06:36 UTC, AbhishekA1509 requested changes

2024-07-23 06:36 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
> +                                <span className='flex dc__align-items-center'>
Please format

2024-07-23 06:36 UTC, AbhishekA1509 commented on src/components/app/list-new/AppList.tsx
> +    const [parsedPayloadOnUrlChange, setParsedPayloadOnUrlChange] = useState(getPayloadFromUrl(location.search, appCount, true).payload)
Please add type

2024-07-24 13:00 UTC, AbhishekA1509 requested changes

2024-08-09 11:22 UTC, vivek-devtron approved these changes

2024-08-09 11:56 UTC, merged