chore: security scans tab ui fixes
devtron-labs/dashboard pull request #1926
Opened 2024-07-29 08:20 UTC by arunjaindev

# Description
Update UI for scans listing
Clear url search filters on clear filters

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas

2024-08-07 09:49 UTC, AbhishekA1509 reviewed
Please resolve sonar cloud comments

2024-08-07 11:16 UTC, AbhishekA1509 requested changes

2024-08-07 11:16 UTC, AbhishekA1509 commented on src/components/security/SecurityScansTab/SecurityScansTab.tsx
> +                        <div className="display-grid table__row-grid show-shimmer-loading dc__gap-16 px-20 py-10">
Please add key

2024-08-07 11:16 UTC, AbhishekA1509 commented on src/components/security/SecurityScansTab/SecurityScansTab.tsx
> +            if (searchKey || severity.length || cluster.length || environment.length) {
can create a variable areFiltersActive

2024-08-09 08:04 UTC, arunjaindev commented on src/components/security/SecurityScansTab/utils.tsx
> +export const getSeverityWithCount = (severityCount: SeverityCount) => {
will pick later

2024-08-12 05:22 UTC, AbhishekA1509 commented on src/components/security/SecurityScansTab/constants.tsx
> +    { label: 'Application', value: 'appName' },
I think we have a enum for this value

2024-08-12 05:23 UTC, AbhishekA1509 commented on src/components/security/SecurityScansTab/SecurityScansTab.tsx
> +                        containerClassName="flex-grow-1"
I think we should add max-width

2024-08-12 05:25 UTC, AbhishekA1509 commented on src/components/security/SecurityScansTab/SecurityScansTab.tsx
> +            <span className="fs-12 lh-20 fw-6 cn-7">
Ideally should be a div

2024-08-12 05:25 UTC, AbhishekA1509 commented on src/components/security/SecurityScansTab/SecurityScansTab.tsx
> +            <span className="fs-12 lh-20 fw-6 cn-7">
Same here

2024-08-12 05:31 UTC, AbhishekA1509 commented on src/components/security/SecurityScansTab/SecurityScansTab.tsx
> +    if (!scanListLoading && scanListError) {
We need getIsRequestAborted as well here, please test those cases as well

2024-08-12 05:31 UTC, AbhishekA1509 commented on src/components/security/SecurityScansTab/SecurityScansTab.tsx
> +        if (scanListLoading) {
need || getIsRequestAborted(error)

2024-08-12 05:48 UTC, AbhishekA1509 commented on src/services/service.ts
>      const critical = vulnerabilities
.

2024-08-12 06:30 UTC, arunjaindev commented on src/services/service.ts
>      const critical = vulnerabilities
parsing is not same, some keys are missing in fe-common

2024-08-12 07:22 UTC, AbhishekA1509 approved these changes

2024-08-12 07:23 UTC, AbhishekA1509 approved these changes
Please add type on SEARCH_TYPE_OPTIONS as well

2024-08-12 07:39 UTC, vivek-devtron approved these changes

2024-08-21 07:54 UTC, vivek-devtron approved these changes

2024-08-21 08:02 UTC, merged