chore: refactor dc__striped-row into dc__striped-table
devtron-labs/dashboard pull request #1927
Opened 2024-07-29 09:46 UTC by Elessar1802

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-07-29 10:02 UTC, eshankvaish requested changes

2024-07-29 11:15 UTC, Elessar1802 commented on src/css/base.scss
> +.dc__striped-table {
nope. The counting starts with 1. The first row is actually the header. And if you see inside dc__striped-table we overriding the odd stylings for the first element.

2024-07-29 13:36 UTC, eshankvaish approved these changes

2024-07-30 07:16 UTC, eshankvaish approved these changes

2024-07-30 07:16 UTC, merged