feat: add new tab to migrate helm release in CD
devtron-labs/dashboard pull request #1949
Opened 2024-08-07 09:51 UTC by arunjaindev

# Description
Add support for migrating helm release in CD Build Pipeline

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas

2024-08-09 07:55 UTC, AbhishekA1509 requested changes

2024-08-09 07:55 UTC, AbhishekA1509 commented on src/css/base.scss
> +.dc__border-b2 {
can use eb-2 bw-1, please revert

2024-08-09 07:55 UTC, AbhishekA1509 commented on src/components/cdPipeline/BuildCD.tsx
> +    const  renderEnvSelector = () => {
please format

2024-08-09 07:55 UTC, AbhishekA1509 commented on src/components/cdPipeline/BuildCD.tsx
> +                    options={releaseMode === ReleaseMode.LINK ? envList.filter((env) => !env.isVirtualEnvironment) : envList}
Can we rename ReleaseMode.Link to something readable

2024-08-09 07:55 UTC, AbhishekA1509 commented on src/components/cdPipeline/BuildCD.tsx
> +        const getNamespaceplaceholder = (): string => {
Can follow camelCase

2024-08-09 07:55 UTC, AbhishekA1509 commented on src/components/cdPipeline/BuildCD.tsx
> +            if (isVirtualEnvironment) {
Can we move this method outside this method it is anti pattern to have methods in methods

2024-08-09 07:55 UTC, AbhishekA1509 commented on src/components/cdPipeline/CDPipeline.tsx
> +        const getButtonDisabledMessage = (): string => {
please wrap in curly braces

2024-08-12 08:02 UTC, AbhishekA1509 submitted a review, later dismissed

2024-08-16 08:29 UTC, vivek-devtron commented on src/components/cdPipeline/cdpipeline.util.tsx
> +        if (namespace) {
We should reverse this check to remove duplicity

2024-08-16 08:35 UTC, vivek-devtron commented on src/components/app/details/appDetails/SourceInfo.tsx
> +                          {!loadingResourceTree && !helmMigratedAppNotTriggered && (
We should add wrap a common check of `!helmMigratedAppNotTriggered`

2024-08-16 08:39 UTC, vivek-devtron commented on src/components/cdPipeline/BuildCD.tsx
> +                <ReactSelect<OptionType, false>
can we use common selectPicker here?

2024-08-21 12:32 UTC, vivek-devtron approved these changes

2024-08-23 05:39 UTC, vivek-devtron approved these changes

2024-08-23 05:39 UTC, merged