feat: dynamic code editor height in sso login component
devtron-labs/dashboard pull request #1971
Opened 2024-08-16 05:23 UTC by Elessar1802

# Description

Dynamically adjust the height of the code editor in sso login component such that the scroll inside code editor does not appear

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-08-16 05:42 UTC, AbhishekA1509 commented on src/Pages/GlobalConfigurations/Authorization/SSOLoginServices/SSOLogin.component.tsx
> +                            <div className="flex dc__content-space">
Can we add some dc__gap so that error and toggle may not stick

2024-08-16 05:47 UTC, AbhishekA1509 requested changes

2024-08-16 05:47 UTC, AbhishekA1509 commented on src/Pages/GlobalConfigurations/Authorization/SSOLoginServices/SSOLogin.component.tsx
> +                        height={250}
Do we need to give height when adjustEditorHeightToContent

2024-08-16 05:47 UTC, AbhishekA1509 commented on src/components/login/login.scss
> +.code-editor-container > .react-monaco-editor-container {
Why do we need this?

2024-08-16 07:20 UTC, AbhishekA1509 submitted a review, later dismissed

2024-08-16 08:50 UTC, AbhishekA1509 submitted a review, later dismissed

2024-08-23 06:16 UTC, vivek-devtron approved these changes

2024-08-23 12:49 UTC, vivek-devtron submitted a review, later dismissed

2024-08-23 12:52 UTC, vivek-devtron approved these changes

2024-08-23 12:52 UTC, merged