chore: replace tab-list class with tab group component
devtron-labs/dashboard pull request #1982
Opened 2024-08-21 13:04 UTC by RohitRaj011

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas

2024-08-30 05:07 UTC, eshankvaish requested changes

2024-08-30 05:07 UTC, eshankvaish commented on src/components/app/details/AppHeader.tsx
> +                showWarning: !!showWarning,
is this a custom prop?

2024-08-30 05:12 UTC, RohitRaj011 commented on src/components/app/details/AppHeader.tsx
> +                showWarning: !!showWarning,
discussed

2024-08-30 05:13 UTC, RohitRaj011 commented on src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
> +        const tabs: TabProps[] = [
no, the height is same

2024-08-30 05:28 UTC, eshankvaish submitted a review, later dismissed

2024-08-30 12:52 UTC, vivek-devtron approved these changes

2024-09-05 05:50 UTC, vivek-devtron approved these changes

2024-09-05 06:01 UTC, merged