Feat/replace select picker
devtron-labs/dashboard pull request #2002
Opened 2024-08-29 06:31 UTC by shivani170

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-09-04 12:32 UTC, RohitRaj011 requested changes

2024-09-04 12:32 UTC, RohitRaj011 commented on src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
> +                        <span className="pl-16 pr-16">Select image by release tag</span>
```suggestion
                        <span className="px-16">Select image by release tag</span>
```

2024-09-04 12:32 UTC, RohitRaj011 commented on src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
> +                        <div style={{ zIndex: 1 }} className="tag-selection-dropdown pr-16 pl-16 pt-6 pb-12">
same

2024-09-04 12:32 UTC, RohitRaj011 commented on .eslintignore
> +src/components/charts/modal/deployChart.types.ts
why add this ?

2024-09-04 12:40 UTC, shivani170 commented on .eslintignore
> +src/components/charts/modal/deployChart.types.ts
removed

2024-09-05 05:16 UTC, RohitRaj011 approved these changes

2024-09-09 06:56 UTC, vivek-devtron commented on src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
> -                        {currentSidebarTab === CDMaterialSidebarType.IMAGE && (
Is it intentional?

2024-09-09 06:58 UTC, vivek-devtron commented on src/components/app/details/AboutAppInfoModal.tsx
> +                inputId='overview-project-menu-list'
We should use " instead of ' in html

2024-09-09 10:39 UTC, shivani170 commented on src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
> -                        {currentSidebarTab === CDMaterialSidebarType.IMAGE && (
No it's not. reverted back

2024-09-09 10:44 UTC, merged