refactor: Application Group Overview Table Revamp, feat: create EnvironmentOverviewTable
devtron-labs/dashboard pull request #2004
Opened 2024-08-29 12:40 UTC by RohitRaj011

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas

2024-09-03 09:51 UTC, eshankvaish requested changes

2024-09-03 09:51 UTC, eshankvaish commented on src/components/ApplicationGroup/Details/EnvironmentOverview/envOverview.scss
> +    overflow: auto;
- Check for using from utils
- Check if any of the css can be removed

2024-09-03 09:51 UTC, eshankvaish commented on src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
> -            appInfoList: _appListData.appInfoList.sort((a, b) => {
```suggestion
            appInfoList: _appListData.appInfoList.sort((a, b) => {
```

2024-09-03 09:51 UTC, eshankvaish commented on src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
> +    }, [searchParams.sortBy, searchParams.sortOrder])
We can possibly move to the component; and use memo

2024-09-03 09:51 UTC, eshankvaish commented on src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
> +    const environmentOverviewTableRows = appListData?.appInfoList?.map((appInfo) => ({
add type

2024-09-03 09:51 UTC, eshankvaish commented on src/Pages/Shared/EnvironmentOverviewTable/EnvironmentOverviewTable.component.tsx
> +                            </PopupMenu>
suggestion: abstract to a separate component

2024-09-09 07:54 UTC, eshankvaish approved these changes

2024-09-09 10:44 UTC, eshankvaish approved these changes

2024-09-11 10:50 UTC, vivek-devtron approved these changes

2024-09-16 05:33 UTC, vivek-devtron approved these changes

2024-09-16 05:34 UTC, merged