feat: Manifest Config Diff - Comparison of Manifest Output
devtron-labs/dashboard pull request #2022
Opened 2024-09-05 05:07 UTC by RohitRaj011

# Description

Add support for manifest comparison in deployment config diff.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas

2024-09-09 13:10 UTC, eshankvaish requested changes

2024-09-09 13:10 UTC, eshankvaish commented on src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/utils.ts
> +    )
common out and add try catch as discussed

2024-09-09 13:10 UTC, eshankvaish commented on src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/service.utils.ts
> +} & Pick<DeploymentConfigCompareProps, 'type' | 'environments'>) => {
migrate the types to types file

2024-09-09 13:10 UTC, eshankvaish commented on src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/service.utils.ts
> +    }
check if this can be DRY'ed out

2024-09-09 13:10 UTC, eshankvaish commented on src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
> +    const isManifestView = resourceType === EnvResourceType.Manifest
move this above line 61 and reuse there as well

2024-09-09 13:10 UTC, eshankvaish commented on src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
> +        () => Promise.all([getOptions(compareToAppId, compareToEnvId), getOptions(compareWithAppId, compareWithEnvId)]),
confirm if abort controller is required

2024-09-09 13:10 UTC, eshankvaish commented on src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
> +                  (isConfigTypeNonDraftOrPublished(compareWithConfigType) ? !!compareWithManifestChartRefId : true)
```suggestion
                  (!isConfigTypeNonDraftOrPublished(compareWithConfigType) || !!compareWithManifestChartRefId)
```

2024-09-09 13:47 UTC, RohitRaj011 commented on src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
> +        () => Promise.all([getOptions(compareToAppId, compareToEnvId), getOptions(compareWithAppId, compareWithEnvId)]),
not required

2024-09-10 06:55 UTC, eshankvaish submitted a review, later dismissed

2024-09-13 05:49 UTC, vivek-devtron commented on src/Pages/Applications/DevtronApps/Details/AppConfigurations/AppConfig.types.ts
> +export type GetDeploymentTemplateDataProps = Pick<DeploymentConfigCompareProps, 'type' | 'appName' | 'envName'> & {
Instead of this We should omit the unwanted values of GetConfigDiffDataProps

2024-09-13 08:14 UTC, vivek-devtron approved these changes

2024-09-16 05:45 UTC, vivek-devtron approved these changes

2024-09-16 05:46 UTC, merged