feat: replace select v4
devtron-labs/dashboard pull request #2061
Opened 2024-09-17 13:15 UTC by shivani170

#Description

- [x] App Details > Environment 

- [x]  EnvironmentList.tsx
    - [x] 1. Sidebar => Job > Trigger job > Excute job in
    ![Image](https://github.com/user-attachments/assets/c21e62a5-3537-4bc2-b238-b3bdd1116a54)

    - [x] 2.  ciMaterial.tsx => CI pipeline.tsx > Jobs > Configuration > Createjob  > Sidebar > Execute tasks in environment
    ![Image](https://github.com/user-attachments/assets/791fcdf7-f363-4c41-aa1f-ed8825f3b8c6)

-[x] ciCreateDockerFileOption.tsx => Create DockerFile
<img width="679" alt="Screenshot 2024-09-30 at 4 08 01 PM" src="https://github.com/user-attachments/assets/1777a0f8-044b-456e-bf5f-213aabc349de">

 - [x] CIBuildpackBuildOptions => Select DockerFile
     - [x] Select repository containing code
     - [x] Language
     - [x] Version.
     
 - [x] ciConfig > CreateDockerFileLanguageOptions.tsx
 - [x] BuildContext
     - [x] Select repo containing build contex
     - [x]  Build Context Path (Relative)
- [x] ChartValueEditor.tsx
![Image](https://github.com/user-attachments/assets/de62b50a-f11d-4eb1-b60d-a7fb31089c3e)

- EnvConfigurationNAv
   - [x] App Group > configuration > Application => ApplicationRoutes.tsx
   - ![Image](https://github.com/user-attachments/assets/7b25b309-2f79-4772-9ba9-44e26d071108)
   - [x] Devtron Apps > configuration > Application => AppNavigations.tsx
   - ![Image](https://github.com/user-attachments/assets/2a4d3bdb-d90e-4a01-ae28-f5f4bae49646)

- EnvironmentOverrideRouter.tsx
   - [x] Job > configuration > Add environment
   - ![Image](https://github.com/user-attachments/assets/e29f4271-3bee-4ccb-a734-6f340beee94f)

- [x[ ExpirationDate > API Token
- [x] LinkedCIDetail Modal > Environment

--------------------------------------------------------------------------------------

Existing Bugs:

1. [x] Devtron/Helm App Details page:
<img width="646" alt="Screenshot 2024-10-01 at 3 42 25 PM" src="https://github.com/user-attachments/assets/df9dcf6f-f50d-43c9-a147-4ec97206a46e">
2. [x] Min Size reduces to 56px from 100px > assignment operator in task
<img width="485" alt="Screenshot 2024-10-01 at 3 45 23 PM" src="https://github.com/user-attachments/assets/13dab133-6a22-403f-ae2f-f291356bf853">

--------------------------------------Targeted area------------------------------------------------------------

![Image](https://github.com/user-attachments/assets/e39a5074-62e4-493c-b602-8f77e0490566)

----------------------------------------------------------------------------------------------------------------

Fixes https://github.com/devtron-labs/sprint-tasks/issues/851

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-09-24 19:11 UTC, RohitRaj011 requested changes

2024-09-24 19:11 UTC, RohitRaj011 commented on src/components/common/helpers/Helpers.tsx
> +export function createClusterEnvGroup<T, K = T>(
why?

2024-09-24 19:11 UTC, RohitRaj011 commented on src/components/ciConfig/utils.tsx
> +export const getGitRepositoryOptions = (sourceMaterials) =>
suggestion: can add types for params

2024-09-24 19:11 UTC, RohitRaj011 commented on src/components/ciConfig/CIConfigForm.tsx
> +              const getCurrentMaterial = (): SelectedGitMaterialType => {
formatting seems off

2024-09-24 19:11 UTC, RohitRaj011 commented on src/components/ciConfig/CIConfigForm.tsx
> +              const getParsedSourceConfig = (): SourceConfigType => {
can move this and above function to utils

2024-09-24 19:11 UTC, RohitRaj011 commented on src/components/cdPipeline/BuildCD.tsx
> +        const selectedEnv: EnvironmentOptionWithSelectPicker = _environment &&{
lets disc this logic

2024-09-24 19:11 UTC, RohitRaj011 commented on src/components/app/details/triggerView/types.ts
> +    selectedEnv?: EnvironmentOptionWithSelectPicker
whats this type

2024-09-30 17:30 UTC, shivani170 commented on src/components/common/helpers/Helpers.tsx
> +export function createClusterEnvGroup<T, K = T>(
Reverted the changes

2024-10-01 11:52 UTC, vivek-devtron commented on src/components/app/details/appDetails/AppDetails.tsx
> +                    // components={{
Please remove commented code if not required

2024-10-01 11:54 UTC, vivek-devtron commented on src/components/cdPipeline/BuildCD.tsx
> +            value: _environment,
Please verify if _environment as value is reuired

2024-10-01 11:59 UTC, vivek-devtron commented on src/components/ciConfig/CICreateDockerfileOption.tsx
> +import { getGitProviderIcon } from '@Components/common'
Please remove this unused icon

2024-10-01 12:04 UTC, vivek-devtron commented on src/components/ciConfig/CIConfigForm.tsx
> +            return { ..._material, value: _material.checkoutPath, label: _material.name, startIcon: getGitProviderIcon(_material.url) }
Please format the code

2024-10-01 12:08 UTC, vivek-devtron commented on src/components/CIPipelineN/EnvironmentList.tsx
> +            value: selectedEnv, // assuming the whole object is set as value
Please verify if it is reuired

2024-10-04 04:14 UTC, RohitRaj011 approved these changes

2024-10-04 13:07 UTC, vivek-devtron commented on src/components/ciConfig/CIConfig.tsx
> +                const sourceConfigMaterial = sourceConfig.material?.map((material: MaterialOptionType) => {
Should we add some default value here?

2024-10-04 13:09 UTC, vivek-devtron commented on src/components/ciConfig/CIConfigForm.tsx
> +            ...(material ? material : currentMaterial),
Why are we spreading material and for label and value using currentMaterial. It can cause data discripencies in some case

2024-10-04 13:10 UTC, vivek-devtron commented on src/components/ciConfig/CIConfigForm.tsx
> +        _sourceConfig.material = _sourceConfig.material.map((_material) => {
Can we directly write it as 
```suggestion
        _sourceConfig.material = _sourceConfig.material.map(getParsedCurrentMaterial(_material))
```

2024-10-07 15:56 UTC, vivek-devtron commented on dashboard.code-workspace
Why are we adding this file?

2024-10-07 16:02 UTC, vivek-devtron submitted a review, later dismissed

2024-10-07 16:13 UTC, Elessar1802 approved these changes

2024-10-07 16:19 UTC, merged