feat: add support to expand/collapse all log accordions at once
devtron-labs/dashboard pull request #2073
Opened 2024-09-20 07:16 UTC by Elessar1802

# Description

As the PR tittle suggests

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-09-20 12:18 UTC, AbhishekA1509 approved these changes

2024-09-20 15:09 UTC, Elessar1802 commented
@AbhishekA1509 moved the css for log resize button to common

2024-09-23 04:57 UTC, AbhishekA1509 approved these changes

2024-09-23 06:57 UTC, AbhishekA1509 commented on src/components/v2/appDetails/appDetails.type.ts
> +    clusterName: string
Can we extend this

2024-09-23 07:12 UTC, AbhishekA1509 commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
> +                    <ICDevtronLogo className="fcn-0 icon-dim-16" />
Please add no shrink to this

2024-09-23 07:21 UTC, AbhishekA1509 requested changes
@abhibhaw In future we may have to give the existing features like resuming disconnected state and actions tile in full screen mode as well

2024-09-23 07:22 UTC, AbhishekA1509 submitted a review, later dismissed

2024-09-23 08:36 UTC, AbhishekA1509 approved these changes

2024-09-23 08:44 UTC, vivek-devtron submitted a review, later dismissed

2024-09-23 10:51 UTC, abhibhaw commented
> @abhibhaw In future we may have to give the existing features like resuming disconnected state and actions tile in full screen mode as well

Agreed @AbhishekA1509

2024-09-23 11:06 UTC, vivek-devtron submitted a review, later dismissed

2024-09-23 12:29 UTC, vivek-devtron approved these changes

2024-09-23 12:29 UTC, merged