feat: config drift modal
devtron-labs/dashboard pull request #2112
Opened 2024-10-08 14:12 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-10-09 13:23 UTC, eshankvaish requested changes

2024-10-09 13:23 UTC, eshankvaish commented on src/components/v2/appDetails/appDetails.type.ts
> +        normalizedLiveManifest: string
add js doc

2024-10-09 13:23 UTC, eshankvaish commented on src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
> +                                            {getNodeStatus(node)}
let's create a variable for getNodeStatus and reuse

2024-10-09 13:23 UTC, eshankvaish commented on src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
> +                                    {node.hasDrift && (
```suggestion
                                    {node?.hasDrift && (
```

2024-10-09 13:23 UTC, eshankvaish commented on src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
> +                                            {node?.health?.status && <span className="dc__bullet mw-4" />}
```suggestion
                                            {node.health?.status && <span className="dc__bullet mw-4" />}
```

2024-10-09 13:23 UTC, eshankvaish commented on src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
> +                                            {node?.health?.status && <span className="dc__bullet mw-4" />}
We can move this part to ent and pass down the node to it

2024-10-09 13:23 UTC, eshankvaish commented on src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts
> +        return getDesiredAndLiveManifest(requestData)
pass down signal

2024-10-09 13:23 UTC, eshankvaish commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
> +                    <div data-testid="app-resource-container-header" className="flex left">
undo

2024-10-09 13:23 UTC, eshankvaish commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
> +        : appDetails.resourceTree.nodes.filter(
check for null checks

2024-10-09 13:23 UTC, eshankvaish commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
> +                            response[0]?.result?.manifestResponse?.manifest || response[0]?.result?.liveState || '',
reverse the condition as discussed

2024-10-09 13:23 UTC, eshankvaish commented on src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
> +                                    </div>
move to FE lib

2024-10-09 13:23 UTC, eshankvaish commented on src/components/app/list-new/list.utils.ts
> +                options: clusterItem.options.sort((a, b) => stringComparatorBySortOrder(a.label, b.label)),
add null check

2024-10-09 13:23 UTC, eshankvaish commented on src/components/app/details/appDetails/SourceInfo.tsx
> +                )}
or we can can not of isVirtual
```suggestion
                {appDetails?.resourceTree && !isIsolatedEnv && ConfigSyncStatusButton && (
                    <div className="pl-8">
                        <ConfigSyncStatusButton
                            areConfigurationsDrifted={appDetails.resourceTree.hasDrift}
                            appId={appDetails?.appId}
                            envId={envId}
                        />
                    </div>
                )}
```

2024-10-09 13:23 UTC, eshankvaish commented on src/components/app/details/appDetails/SourceInfo.tsx
> +                            appId={appDetails?.appId}
```suggestion
                            appId={appDetails.appId}
```

2024-10-09 13:23 UTC, eshankvaish commented on src/components/app/details/appDetails/AppDetails.tsx
> +                <AppStatusDetailModal close={hideAppDetailsStatus} showAppStatusMessage={false} showConfigDriftInfo />
showConfigDriftInfo should be based of fe-lib and to be verified for isolated airgapped

2024-10-09 13:23 UTC, eshankvaish commented on src/components/app/details/appDetails/AppDetails.tsx
> +            {ConfigDriftModalRoute && <ConfigDriftModalRoute path={path} />}
route should not be there for virtual

2024-10-14 05:45 UTC, eshankvaish approved these changes

2024-10-21 06:49 UTC, vivek-devtron approved these changes

2024-10-21 12:15 UTC, merged