feat: add swap traffic button
devtron-labs/dashboard pull request #2193
Opened 2024-11-12 09:42 UTC by arunjaindev

# Description
add swap traffic button

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1214

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-11-12 12:00 UTC, AbhishekA1509 requested changes

2024-11-12 12:00 UTC, AbhishekA1509 commented on src/components/app/details/appDetails/SourceInfo.tsx
> +                                    appDetails.pcoId &&
Please convert to boolean: !!appDetails.pcoId

2024-11-12 12:17 UTC, AbhishekA1509 submitted a review, later dismissed

2024-11-13 07:23 UTC, vivek-devtron approved these changes

2025-01-03 06:59 UTC, vivek-devtron approved these changes

2025-01-03 07:01 UTC, merged