chore: conform to new function signatures of copyToClipboard & ClipboardButton
devtron-labs/dashboard pull request #2207
Opened 2024-11-15 11:03 UTC by Elessar1802

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-11-16 16:18 UTC, AbhishekA1509 requested changes

2024-11-16 16:18 UTC, AbhishekA1509 commented on src/components/cluster/ClusterInfoStepsModal.tsx
> +        copyToClipboard(command).catch(noop)
Are we sure  setCopied(true) should happen even in case of error

2024-11-16 16:18 UTC, AbhishekA1509 commented on src/components/ciPipeline/ConfigureWebhook.tsx
> +                            onClick={handleCopyUrl}
Suggestion: These divs should be a button

2024-11-18 06:49 UTC, Elessar1802 commented on src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
> +            <PodIcon color="var(--N400)" style={{ width: '48px', height: '48px', marginBottom: '12px' }} />
PodIcon is actually a react component and not a svg import. style is a prop.

2024-11-18 06:53 UTC, Elessar1802 commented on src/components/common/FloatingVariablesSuggestions/SuggestionItem.tsx
> +    const [copyToClipboardPromise, setCopyToClipboardPromise] = useState<ReturnType<typeof copyToClipboard>>(null)
I need to trigger a re-render to send in this promise as prop to clipboardButton. There storing it in state.

2024-11-18 07:03 UTC, Elessar1802 commented on src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
> +    const clipboardContent = window.location.href
location.href will give me the full path including query params. If i use useLocation I will have to join pathname and search properties to get the full href.

2024-11-18 08:28 UTC, AbhishekA1509 approved these changes

2024-11-18 08:36 UTC, vivek-devtron submitted a review, later dismissed

2024-11-18 10:09 UTC, vivek-devtron approved these changes

2024-11-18 10:10 UTC, merged