feat: persist app group and env group filter in local storage
devtron-labs/dashboard pull request #2209
Opened 2024-11-15 12:53 UTC by arunjaindev

# Description
feat: persist app group and env group filter in local storage

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-11-16 17:09 UTC, AbhishekA1509 requested changes

2024-11-16 17:09 UTC, AbhishekA1509 commented on src/components/ApplicationGroup/AppGroupAppFilter.tsx
> +            setFilterInLocalStorage(filterParentType, resourceId, selectedValue, [])
NOTE: Please discuss this before moving ahead with this comment

Ideally this should be done through useStateFilters or there should be a mechanism to auto sync state with local storage, after discussion can take call.

2024-11-16 17:09 UTC, AbhishekA1509 commented on src/components/ApplicationGroup/AppGroupAppFilter.tsx
> +            const localStorageValue = localStorage.getItem(localStorageKey)
I believe there is some duplication with setFilterInLocalStorage

2024-11-16 17:09 UTC, AbhishekA1509 commented on src/components/ApplicationGroup/AppGroupAppFilter.tsx
> +            const valueForCurrentResource = new Map(JSON.parse(localStorageValue)).get(resourceId)
Please safely parse the local storage value

2024-11-16 17:09 UTC, AbhishekA1509 commented on src/components/ApplicationGroup/AppGroupAppFilter.tsx
> +        if (filterParentType === FilterParentType.app) {
Please move the key into variable based on condition and then set the value

2024-11-16 17:09 UTC, AbhishekA1509 commented on src/components/ApplicationGroup/AppGroupAppFilter.tsx
> +            const filteredLocalStorageResourceList = localStorageResourceList?.filter(({value}) => appListOptionsMap[value])
Can add fallback into variable directly instead of null check here

2024-11-18 08:04 UTC, AbhishekA1509 approved these changes

2024-11-18 08:16 UTC, vivek-devtron approved these changes

2024-11-18 08:29 UTC, merged