feat: replace hibernate modal with confirmation dialog
devtron-labs/dashboard pull request #2211
Opened 2024-11-18 11:12 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-11-25 12:28 UTC, AbhishekA1509 requested changes

2024-11-25 12:28 UTC, AbhishekA1509 commented on src/App.tsx
> +                                    <div id="backdrop" />
Can we rename since its too generic

2024-11-25 12:28 UTC, AbhishekA1509 commented on src/components/common/navigation/NavigationRoutes.tsx
> +            <main className={`${_isOnboardingPage ? 'no-nav' : ''}`} id='devtron-base-main-identifier'>
Please use constant from fe-common

2024-11-25 12:28 UTC, AbhishekA1509 commented on src/components/common/navigation/NavigationRoutes.tsx
>          >
We can directly use _isOnboardingPage ? 'no-nav' : ''

2024-11-25 12:28 UTC, AbhishekA1509 commented on src/components/app/details/appDetails/AppDetails.tsx
>  import AppNotDeployedIcon from '../../../../assets/img/app-not-deployed.png'
Suggestion: Can we use alias import?

2024-11-26 05:41 UTC, AbhishekA1509 submitted a review, later dismissed

2024-11-28 12:02 UTC, vivek-devtron approved these changes

2024-11-28 12:03 UTC, AbhishekA1509 approved these changes

2024-11-28 12:03 UTC, merged