feat: marked version bump
devtron-labs/dashboard pull request #2221
Opened 2024-11-20 13:22 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-11-21 08:27 UTC, AbhishekA1509 requested changes

2024-11-21 08:27 UTC, AbhishekA1509 commented on src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
> +            <span className='fs-13 cn-7 lh-20 fw-4'>How do you want to deploy?</span>
Please format

2024-11-21 08:27 UTC, AbhishekA1509 commented on src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
> +                getOptionValue({
Can move this outside loop

2024-11-25 10:25 UTC, arunjaindev commented on src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
> +                getOptionValue({
only formatting changes here

2024-11-25 13:01 UTC, vivek-devtron approved these changes

2024-11-25 14:23 UTC, AbhishekA1509 approved these changes

2024-11-25 14:38 UTC, vivek-devtron approved these changes

2024-11-25 14:46 UTC, merged