feat: cm secret patch dry run
devtron-labs/dashboard pull request #2232
Opened 2024-11-25 05:07 UTC by RohitRaj011

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1136

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-11-26 12:12 UTC, AbhishekA1509 requested changes

2024-11-28 11:16 UTC, RohitRaj011 commented on src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
> +        const _configMapSecretData = draftData ? JSON.parse(draftData.data).configData[0] : configMapSecretData
not required now

2024-11-29 03:28 UTC, RohitRaj011 commented on src/Pages/Shared/ConfigMapSecret/types.ts
> +    mergeStrategy: ConfigToolbarProps['mergeStrategy']
not required now

2024-11-29 03:29 UTC, RohitRaj011 commented on src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/SelectMergeStrategy.tsx
> +    hidePatchOption,
this is already being handled in ConfigToolbar

2024-11-29 03:31 UTC, RohitRaj011 commented on src/Pages/Shared/ConfigMapSecret/ConfigMapSecretDryRun.tsx
> +                    ...JSON.parse(draftData.data).configData?.[0],
not required now

2024-11-29 03:38 UTC, RohitRaj011 commented on src/Pages/Shared/ConfigMapSecret/ConfigMapSecretDryRun.tsx
> +        let configMapSecretData: CMSecretConfigData =
early returns not possible
moved to util

2024-11-29 03:51 UTC, RohitRaj011 commented on src/Pages/Shared/ConfigMapSecret/ConfigMapSecretApproveButton.tsx
> +export const ConfigMapSecretApproveButton = ({
some utils are present only in dashboard, these are being used at other places as well

2024-11-29 08:20 UTC, AbhishekA1509 commented on src/Pages/Shared/ConfigMapSecret/ConfigMapSecretApproveButton.tsx
> +export const ConfigMapSecretApproveButton = ({
Its only two small utils which should ideally be in common 😅 , but can leave if taking time

2024-12-02 10:42 UTC, AbhishekA1509 commented on src/Pages/Shared/ConfigMapSecret/utils.ts
> +        headerTab: Object.values(ConfigHeaderTabType).includes(headerTab) ? headerTab : null,
Can we use CONFIG_HEADER_TAB_VALUES

2024-12-03 11:24 UTC, vivek-devtron approved these changes

2024-12-04 09:48 UTC, merged