feat: mandatory tags blocks trigger
devtron-labs/dashboard pull request #2246
Opened 2024-12-02 09:46 UTC by arunjaindev

# Description
integrate api changes for mandatory tags on cd modal and materials api

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-12-02 13:02 UTC, AbhishekA1509 requested changes

2024-12-02 13:02 UTC, AbhishekA1509 commented on src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
> +        if (app.triggerBlockedInfo?.blockedBy === TriggerBlockType.MANDATORY_TAG) {
Please set warning and ensure material calls are not going in case we have this error

2024-12-06 07:51 UTC, AbhishekA1509 requested changes

2024-12-06 07:58 UTC, AbhishekA1509 commented on src/components/app/details/triggerView/types.ts
> +    isTriggerBlocked?: boolean
I believe this must be extensible

2024-12-10 08:06 UTC, AbhishekA1509 commented on src/components/app/details/triggerView/workflow/nodes/triggerCDNode.tsx
>  } from '../../../../../workflowEditor/NoGitOpsRepoConfiguredWarning'
Please remove unused imports

2024-12-10 08:07 UTC, AbhishekA1509 commented on src/components/app/details/triggerView/workflow/nodes/triggerPrePostCDNode.tsx
> +                                    className={`workflow-node__trigger-type workflow-node__trigger-type--cd flex fw-6 ${this.getNodeSideHeadingContainerClassName()}`}
please use getNodeSideHeadingAndClass

2024-12-10 08:16 UTC, AbhishekA1509 approved these changes

2024-12-11 04:52 UTC, vivek-devtron approved these changes

2024-12-19 14:54 UTC, merged