feat: add check to open overlay by clicking on icon
devtron-labs/dashboard pull request #2278
Opened 2024-12-11 05:52 UTC by arunjaindev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-12-11 11:43 UTC, AbhishekA1509 requested changes

2024-12-11 11:43 UTC, AbhishekA1509 commented on src/components/externalLinks/ExternalLinks.component.tsx
> +    const openOverlayOnIcon: boolean = `${linkOption.value}`.includes('devtronIframePrimary=false')
Please parse params and check if exists and move this to constant

2024-12-11 11:43 UTC, AbhishekA1509 commented on src/components/externalLinks/ExternalLinks.component.tsx
> +                            ? getHandleOpenURL(externalLinkURL)
Please santize externalLinkURL by removing devtronIframePrimary

2024-12-11 11:43 UTC, AbhishekA1509 commented on src/components/externalLinks/ExternalLinks.component.tsx
> +                        ? { onClick: handleTextClick }
Ideally a tag should contain href

2024-12-11 11:43 UTC, AbhishekA1509 commented on src/components/externalLinks/ExternalLinksCRUD/AddExternalLink.tsx
> +                            &nbsp;<span className="bcn-1 px-4 br-6">devtronIframePrimary=false</span>&nbsp;
Please re-use the constant that we will define now

2024-12-11 11:43 UTC, AbhishekA1509 commented on src/components/externalLinks/ExternalLinksCRUD/AddExternalLink.tsx
> +                            <div key={variable} className="flexbox dc__gap-4 dc__align-items-center dc__visible-hover dc__visible-hover--parent">
Check if truncate or word-break is required

2024-12-11 13:39 UTC, AbhishekA1509 commented on src/components/externalLinks/ExternalLinks.component.tsx
> +    const [baseUrl, searchString] = externalLinkURL.split('?')
Ideally should be done in service itself

2024-12-13 06:09 UTC, AbhishekA1509 submitted a review, later dismissed

2024-12-13 07:52 UTC, AbhishekA1509 submitted a review, later dismissed

2024-12-13 08:06 UTC, vivek-devtron approved these changes

2024-12-13 08:08 UTC, merged