feat: add button to reload resource tree for v1 app details
devtron-labs/dashboard pull request #2300
Opened 2024-12-18 19:35 UTC by Elessar1802

# Description

<img width="1405" alt="Screenshot 2024-12-19 at 1 06 01 AM" src="https://github.com/user-attachments/assets/bbc9dc70-d3d6-41e2-9bf7-ed93056c03b3" />

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1564

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-12-20 08:11 UTC, arunjaindev requested changes

2024-12-20 08:11 UTC, arunjaindev commented on src/components/externalArgoApps/ExternalArgoAppDetail.tsx
>                  setIsLoading(false)
can move in finally and remove from .then and .catch

2024-12-20 12:11 UTC, vivek-devtron submitted a review, later dismissed

2024-12-23 05:52 UTC, vivek-devtron approved these changes

2024-12-23 05:56 UTC, arunjaindev approved these changes

2024-12-23 05:56 UTC, merged