feat: add support for deleted user in user permission csv export
devtron-labs/dashboard pull request #2312
Opened 2024-12-23 08:58 UTC by eshankvaish

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1547

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2024-12-23 11:52 UTC, AbhishekA1509 commented on src/Pages/GlobalConfigurations/Authorization/UserPermissions/List/ExportUserPermissionsToCsv.tsx
> +                ? `${moment(_user.updatedOn).utc().format(Moment12HourExportFormat)} (UTC)`
Can make a util in common since using thrice here and in fe-lib as well

2024-12-23 11:59 UTC, AbhishekA1509 commented on src/components/common/ExportToCsv/ExportToCsv.tsx
> +                <span className="fs-13 fw-4 cb-5 pointer" onClick={initiateDownload}>
Suggestion: Can we move this to button?

2024-12-23 12:02 UTC, AbhishekA1509 requested changes

2024-12-23 12:02 UTC, AbhishekA1509 commented on src/components/common/ExportToCsv/ExportConfiguration.tsx
> +                            <span className="fs-13 fw-4 lh-20 cn-9 dc__truncate">{label}</span>
Do we need tooltip for label and description?

2024-12-23 12:55 UTC, AbhishekA1509 approved these changes

2024-12-24 04:35 UTC, vivek-devtron submitted a review, later dismissed

2024-12-24 08:41 UTC, vivek-devtron approved these changes

2024-12-24 08:42 UTC, merged