feat: Revamp UI of Global Notifictaion Configuration
devtron-labs/dashboard pull request #2318
Opened 2024-12-26 01:20 UTC by shivani170

# Description

feat: Revamp UI of Global Notifictaion Configuration 
<img width="439" alt="Screenshot 2024-12-26 at 6 50 23 AM" src="https://github.com/user-attachments/assets/27d77512-6f5c-40dd-be03-760dc7259d40" />

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas

2025-01-02 04:46 UTC, RohitRaj011 requested changes

2025-01-02 04:46 UTC, RohitRaj011 commented on src/Pages/GlobalConfigurations/ClustersAndEnvironments/ClusterEnvironmentDrawer/ClusterEnvironmentDrawer.tsx
> +                    <div className="dc__overflow-scroll p-20 flex-grow-1">
why?

2025-01-02 04:46 UTC, RohitRaj011 commented on src/components/notifications/ConfigurationTabsSwitcher.tsx
> +                onClick={() => handleAddClick()}
```suggestion
                onClick={handleAddClick}
```

2025-01-02 04:46 UTC, RohitRaj011 commented on src/components/notifications/ConfigurationTabsSwitcher.tsx
> +                        onClick={() => handleTabClick(tab.link)}
inline-function

2025-01-02 04:46 UTC, RohitRaj011 commented on src/components/notifications/ConfigurationTabsSwitcher.tsx
> +                startIcon={<Add className="icon-dim-20" />}
does icon size class have any effect?

2025-01-02 04:46 UTC, RohitRaj011 commented on src/components/notifications/SlackConfigurationTable.tsx
> +            <div className="flex progressing-loader-height">
can common out this loading component

2025-01-02 04:46 UTC, RohitRaj011 commented on src/components/notifications/SlackConfigurationTable.tsx
> +                    <td className="slack-config-table__webhook dc__truncate-text ">Webhook URL</td>
is this correct ?
`WebHook URL`

2025-01-02 04:46 UTC, RohitRaj011 commented on src/components/notifications/WebhookConfigurationTable.tsx
> +export const WebhookConfigurationTable = ({ setState, state, deleteClickHandler }: ConfigurationTableProps) => {
this and `SlackConfigurationTable` seems similar please check if these can be common out

2025-01-02 04:46 UTC, RohitRaj011 commented on .eslintignore
> +src/components/notifications/ConfigurationTab.component.tsx
this file doesn't exist

2025-01-03 09:49 UTC, shivani170 commented on src/components/notifications/SlackConfigurationTable.tsx
> +                    <td className="slack-config-table__webhook dc__truncate-text ">Webhook URL</td>
Yes

2025-01-06 04:07 UTC, RohitRaj011 submitted a review, later dismissed

2025-01-09 11:51 UTC, vivek-devtron commented on src/components/notifications/ConfigurationTab.tsx
> +                setState({ ...state, showCannotDeleteDialogModal: true })
Please remove unneccessary setState

2025-01-09 11:53 UTC, vivek-devtron commented on src/components/notifications/ConfigurationTab.tsx
> +    if (state.isLoading) {
Please remove this duplicated line

2025-01-09 11:57 UTC, vivek-devtron commented on src/components/notifications/ConfigurationTabsSwitcher.tsx
> +                         ${index === getConfigurationTabTextWithIcon().length - 1 ? 'dc__right-radius-4' : ''} ${activeTab === tab.link ? 'bcn-1 fw-6 cn-9' : 'bcn-0'} cn-7`}
`cn-7` should be inside the else case of isActive

2025-01-09 12:05 UTC, vivek-devtron commented on src/components/notifications/SESConfigModal.tsx
> +        .map((region) => ({ label: region.name, value: region.value }))
This should be outside the component

2025-01-09 12:33 UTC, vivek-devtron commented on src/components/notifications/notifications.util.tsx
> +            return SES
Fix the default case

2025-01-09 12:34 UTC, vivek-devtron commented on src/components/notifications/notifications.util.tsx
> +            <button
This should be the new `Button` component.

2025-01-09 12:40 UTC, vivek-devtron commented on src/components/notifications/notifications.util.tsx
> +export const getFormValidated = (isFormValid: FormValidation, fromEmail?: string): boolean => {
Please verify if this is required

2025-01-09 12:48 UTC, vivek-devtron commented on src/components/notifications/SESConfigModal.tsx
> +            setFormValid({
this should be inside the validateForm method

2025-01-09 12:55 UTC, vivek-devtron commented on src/components/notifications/notifications.scss
> -.ses-config-table__email {
Remove these from component

2025-01-09 12:55 UTC, vivek-devtron commented on src/components/notifications/notifications.scss
> +    .configuration-tab__table-row:hover .slack-config-table__action,
We should use visible-hover rather that creating all these

2025-01-09 13:01 UTC, vivek-devtron commented on src/components/notifications/SMTPConfigModal.tsx
> +    }, [smtpConfigId, shouldBeDefault])
Why `shouldBeDefault` is a dependency?

2025-01-09 13:25 UTC, vivek-devtron commented on src/components/notifications/WebhookConfigModal.tsx
> +        if (!getAllFieldsValidated()) {
This code seems duplicated

2025-01-13 07:42 UTC, vivek-devtron approved these changes

2025-01-13 08:17 UTC, merged