feat: bulk trigger deployment in DA workflow
devtron-labs/dashboard pull request #2327
Opened 2024-12-31 14:31 UTC by Elessar1802

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas

2025-01-02 08:24 UTC, AbhishekA1509 commented on src/components/app/details/triggerView/TriggerView.tsx
> +                    <TriggerRouter
Pls rename can include something like workflow action something like that

2025-01-03 06:47 UTC, AbhishekA1509 submitted a review, later dismissed

2025-01-07 07:25 UTC, eshankvaish requested changes

2025-01-07 07:25 UTC, eshankvaish commented on src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
> +                                : {}
I think we want to send [] if runtimeParams[currentAppId] is not defined

2025-01-07 10:46 UTC, Elessar1802 commented on src/components/app/details/triggerView/workflow/Workflow.tsx
> +                                {BulkDeployLink && !!this.props.nodes.some((node) => node.type === 'CD') && (
The type is defined as union of string literals

2025-01-08 08:06 UTC, eshankvaish submitted a review, later dismissed

2025-01-09 08:04 UTC, vivek-devtron approved these changes

2025-01-13 08:34 UTC, vivek-devtron approved these changes

2025-01-13 08:41 UTC, merged